# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('smallImg', models.CharField(max_length=256)),
                ('middleImg', models.CharField(max_length=256)),
                ('bigImg', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=30)),
                ('newPrice', models.CharField(max_length=10)),
                ('oldPrice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sasa_goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sasa_user',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sasa_wheel',
            },
        ),
    ]
