# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20181110_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='maintitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='result',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='goods',
            name='yew',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bigImg',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='goods',
            name='middleImg',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='goods',
            name='newPrice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='oldPrice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quality',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='goods',
            name='smallImg',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
