# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20181110_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.User')),
            ],
            options={
                'db_table': 'sasa_basket',
            },
        ),
    ]
